[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "16.18.1", NODE_ENV = "production" }


[dev]
  command = "npm run start"
  publish = "dist"
  port = 3000
  targetPort = 8181
  NODE_ENV = "development"

[[redirects]]
  from = "/blog/blog/rss/all.rss"
  to = "/feed.xml"

[[redirects]]
  from = "/blog/feed.xml"
  to = "/feed.xml"

[[redirects]]
  from = "/blog/the-refactoring-tales/refactoring-tales.html"
  to = "/refactoring-tales"
